CREATE DATABASE VERDE_ESPERANCA;

CREATE TABLE USUARIO (
    ID_USER INT NOT NULL PRIMARY KEY auto_increment,
    USERNAME VARCHAR(15) NOT NULL,
    SENHA VARCHAR(15) NOT NULL,
    NOME VARCHAR (20) NOT NULL,
    DATA_NASC DATE NOT NULL,
    RG CHAR(9) NOT NULL,
    EMAIL VARCHAR(35) NOT NULL
);

CREATE TABLE DENUNCIA (
	ID_DENUNCIA INT NOT NULL PRIMARY KEY auto_increment,
    DESCRICAO VARCHAR(160) NOT NULL,
	LOCALIDADE VARCHAR(50) NOT NULL,
    CD_STATUS INT DEFAULT 0,
	USUARIO INT NOT NULL
);

CREATE TABLE DOACOES (
	ID_DOACAO INT NOT NULL PRIMARY KEY auto_increment,
    VALOR DOUBLE NOT NULL,
    DATA_REALIZACAO DATE NOT NULL,
    USUARIO INT NOT NULL
);

INSERT INTO USUARIO VALUES (1,"Felipe","123","Felipe",'1997-09-08',"245235924","felipevcsantos@hotmail.com");